

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - user_manager_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - user_manager_network

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: mysql://admin:1234@mysql:3306/user_manager
      CACHE_URL: redis://redis:6379
      CACHE_HOST: redis
    networks:
      - user_manager_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - user_manager_network

networks:
  user_manager_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
